version: "3" 

services:
  flask:
    build: .
    container_name: flask_api
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=Game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zk1082
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:










